service: nestjs-serverless

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1
  timeout: 100

functions:
  main:
    handler: dist/mainserverless.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
