service: nestjs-serverless

plugins:
  - serverless-offline
  - serverless-jetpack

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1

functions:
  main:
    handler: dist/serverless.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'

package:
  exclude:
    - '*'
    - '**/node_modules/aws-sdk/**' # included on Lambda.
    - '!package.json'
